### ISSUE TITLE
'isPageHeading': True does not work with file-upload macro

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [LandRegistry/govuk-frontend-jinja#32]
**Describe the bug**
'isPageHeading': True does not work with file-upload macro

**To Reproduce**
Go to "With label as page heading" on https://govuk-frontend-jinja.herokuapp.com/components/file-upload

**Expected behavior**
"Upload a file" should look like a heading 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser:  chrome
 - Version: 97.0.4692.71

**Comment by matthew-shaw** [comment]
Hi @SoumayaMauthoorMOJ thanks for raising this issue and apologies it's taken a while to get back to you. After a bit of investigation it seems that you also have to add additional classes to the label in the macro to make it look like a regular page heading. This page has the details on what classes are available for this: https://design-system.service.gov.uk/get-started/labels-legends-headings/

So for example adding to a file upload component macro:
```
{{ govukFileUpload({
  'id': "file-upload-1",
  'name': "file-upload-1",
  'label': {
    'text': "Upload a file",
    'isPageHeading': True,
    'classes': "govuk-label--l"
  }
}) }}
```

Results in this output:
![image](https://user-images.githubusercontent.com/2802973/167608853-d6b73113-8917-42b8-a566-ff5b9e0cbba4.png)

The reason the demo site isn't showing this correctly is due to the govuk-frontend test fixtures not adding in the required class. I've let the GDS team know and will be opening a PR to add them in. Once that's merged and released then the demo site will also render the page heading options correctly.

Hope this resolves the issue for you. Thanks 😄
